version: "3.9"

services:
  redis:
    profiles:
      - redis
      - all
    image: redis:7.0.7-alpine
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=admin
    ports:
      - '6379:6379'